Disable broken test
Why this test was previously working?
Before this PR, all queries were treated as prepared queries.
When this was changes, to not prepared(*), the error no longer relies
on the js code, ensuring correct amount of parameters (see cql utils: parseParams)
and now relies on the error returned by the database.

With the lack of correct error mapping between rust driver and js driver,
the error currently thrown is no longer Response error, but other error type:

GenericFailure
Error: Error#Serializing values failed: SerializationError:
Failed to type check query arguments
alloc::vec::Vec<core::option::Option<scylla_cql::frame::response::result::CqlValue>>:
wrong column count: the statement operates on 2 columns, but the given rust type provides 1